version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8000:8000'
    tty: true
    volumes:
      - ./backend:/backend
    env_file: backend/.env

  db:
    image: postgres:13.4
    ports:
      - "5432:5432"
    env_file: backend/.env